testing/urls.py
from django.urls import path
from .views import home,statistics,bug_detail,bug_edit,delete_bug,runall_autotests,create_bug,bug_list,auto_test_list,auto_test_delete,auto_test_detail,auto_test_create,auto_test_edit,run_auto_test,update_testplanstatus,edit_testplan,delete_testplan,testplan_details,test_plans,create_testplan,create_checklist,delete_Checklist,edit_checklist, update_checkstatus,checklist_details, checklist_list,tests,manual_tests,test_case_create,test_case_details,test_case_delete,edit_test_case,update_status

app_name = 'testing'

urlpatterns = [
    
    path('', home, name='home'),
    path('tests/', tests, name='tests'),
    path('manual_tests/', manual_tests, name='manual_tests'),
    #path('test_plans/', test_plans, name='test_plans'),
    path('manual_tests/create/', test_case_create, name='create_test_case'),
    path('test-case-details/<int:id>/', test_case_details, name='test_case_details'),
    path('delete_test_case/<int:case_id>/', test_case_delete, name='delete_test_case'),
    path('test_case/<int:case_id>/edit/', edit_test_case, name='edit_test_case'), 
    path('update_status/<int:case_id>/', update_status, name='update_status'),

    path('check_list/create/', create_checklist, name='create_checklist'),
    path('check_list/', checklist_list, name='check_list'),
    path('checklist_details/<int:id>/', checklist_details, name='checklist_details'),
    path('delete_checklist/<int:checklist_id>/', delete_Checklist, name='delete_Checklist'),
    path('check_list/<int:checklist_id>/edit/', edit_checklist, name='edit_checklist'), 
    path('update_checkstatus/<int:checklist_id>/', update_checkstatus, name='update_checkstatus'),

    path('test_plans/create/', create_testplan, name='testplan_create'),
    path('test_plans/', test_plans, name='test_plans'),
    path('testplan_details/<int:id>/', testplan_details, name='testplan_details'),
    path('delete_testplan/<int:testplan_id>/', delete_testplan, name='delete_testplan'),
    path('test_plans/<int:testplan_id>/edit/', edit_testplan, name='edit_testplan'), 
    path('update_testplanstatus/<int:testplan_id>/', update_testplanstatus, name='update_testplanstatus'),


    path('auto_tests/', auto_test_list, name='auto_test_list'),
    path('auto_tests/<int:pk>/', auto_test_detail, name='auto_test_detail'),
    path('auto_tests/new/', auto_test_create, name='auto_test_create'),
    path('auto_tests/<int:pk>/edit/', auto_test_edit, name='auto_test_edit'),
    path('auto_tests/<int:pk>/run/', run_auto_test, name='run_auto_test'),
    path('<int:pk>/delete/', auto_test_delete, name='auto_test_delete'),
    path('run_all/', runall_autotests, name='runall_autotests'),

    path('create_bug/', create_bug, name='create_bug'),
    path('bug_list/', bug_list, name='bug_list'),
    path('delete_bug/<int:bug_id>/', delete_bug, name='delete_bug'),
    path('bug_detail/<int:pk>/', bug_detail, name='bug_detail'),
    path('bug/<int:bug_id>/edit/', bug_edit, name='bug_edit'), 

     path('statistics/', statistics, name='statistics'),
]

tms/urls.py
# В файле tms/urls.py
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testing/', include('testing.urls')),
    path('', RedirectView.as_view(url='/testing/', permanent=True)),  # Добавить перенаправление на /testing/
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



testing/forms.py
from django import forms
from .models import TestCase, Checklist, TestPlan, Bug
from .models import AutoTest

class AutoTestForm(forms.ModelForm):
    class Meta:
        model = AutoTest
        fields = ['name', 'description', 'test_file']

    def __init__(self, *args, **kwargs):
        super(AutoTestForm, self).__init__(*args, **kwargs)
        self.fields['test_file'].widget = forms.FileInput(attrs={'class': 'custom-file-input'})

class TestCaseForm(forms.ModelForm):
    class Meta:
        model = TestCase
        fields = ['name', 'description', 'steps', 'expected_result']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'steps': forms.Textarea(attrs={'class': 'form-control'}),
            'expected_result': forms.Textarea(attrs={'class': 'form-control'}),
        }

class ChecklistForm(forms.ModelForm):
    class Meta:
        model = Checklist
        fields = ['name','description']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

class TestPlanForm(forms.ModelForm):
    class Meta:
        model = TestPlan
        fields = ['name', 'description', 'start_date', 'end_date', 'priority']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'priority': forms.Select(attrs={'class': 'form-control'}),
        }


class BugForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields = ['summary', 'description', 'priority']

testing/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TestPlan
from .forms import TestCaseForm,ChecklistForm, TestPlanForm,BugForm
from .models import TestCase,Checklist, TestPlan,Bug
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.urls import reverse
from .models import AutoTest
from .forms import AutoTestForm
import subprocess
import datetime
import os
from jira import JIRA
from django.conf import settings
import logging




def auto_test_delete(request, pk):
    auto_test = get_object_or_404(AutoTest, pk=pk)
    auto_test.delete()
    return redirect('testing:auto_test_list')

def home(request):
    return render(request, 'testing/home.html')

def checklist_list(request):
    checklists = Checklist.objects.all()
    return render(request, 'testing/check_list.html', {'checklists': checklists})

def create_checklist(request):
    checklists = Checklist.objects.all()
    if request.method == 'POST':
        form = ChecklistForm(request.POST)
        if form.is_valid():
            form.save()
            form = ChecklistForm()  # Очистка формы для нового ввода
            return redirect('/testing/check_list/')
    else:
        form = ChecklistForm()
    filter_type = request.GET.get('filter')
    if filter_type == 'id-sort':
        id_sort = request.GET.get('id-sort')
        if id_sort == 'asc':
            checklist = checklist.order_by('id')
        elif id_sort == 'desc':
            checklist = checklist.order_by('-id')
    elif filter_type == 'name':
        name = request.GET.get('name')
        if name:
            checklist = checklist.filter(name__icontains=name)
    elif filter_type == 'status':
        status = request.GET.get('status')
        if status:
            checklist = checklist.filter(status=status)

    return render(request, 'testing/checklist_create.html', {'form2': form, 'checklists': checklists})


def manual_tests(request):
    cases = TestCase.objects.all()

    filter_type = request.GET.get('filter')
    if filter_type == 'id-sort':
        id_sort = request.GET.get('id-sort')
        if id_sort == 'asc':
            cases = cases.order_by('id')
        elif id_sort == 'desc':
            cases = cases.order_by('-id')
    elif filter_type == 'name':
        name = request.GET.get('name')
        if name:
            cases = cases.filter(name__icontains=name)
    elif filter_type == 'status':
        status = request.GET.get('status')
        if status:
            cases = cases.filter(status=status)

    return render(request, 'testing/manual_tests.html', {'cases': cases})


def tests(request):
    return render(request, 'testing/sidebar.html', {'title': 'Тест-планы'})


def test_case_create(req):
    if req.method == 'POST':
        modelform_case = TestCaseForm(req.POST)
        if modelform_case.is_valid():
            modelform_case.save()
            modelform_case = TestCaseForm()  
    else:
        modelform_case = TestCaseForm()
    cases = TestCase.objects.all().order_by('id')
  
    return render(req, 'testing/create_test_case.html', {'form': modelform_case, 'cases': cases})

def test_case_delete(req, id_case):
    case = get_object_or_404(TestCase, id=id_case)
    if req.method == 'POST':
        case.delete()
        return redirect('testing:manual_tests') 
    return render(req, 'testing/delete_test_case.html', {'case': case})

def delete_Checklist(request, checklist_id):
    checklist = get_object_or_404(Checklist, id=checklist_id)
    if request.method == 'POST':
        checklist.delete()
        return redirect('testing:check_list')
    return render(request, 'testing/delete_checklist.html', {'checklist': checklist})

def edit_test_case(request, case_id):
    case = get_object_or_404(TestCase, id=case_id)
    cases = TestCase.objects.all()
    if request.method == 'POST':
        form = TestCaseForm(request.POST, instance=case)
        if form.is_valid():
            form.save()
            return redirect(reverse('testing:test_case_details', kwargs={'id': case.id}))  
    else:
        form = TestCaseForm(instance=case)
    return render(request, 'testing/edit_test_case.html', {'form': form, 'case': case,'cases': cases})

def edit_checklist(request, checklist_id):
    checklist = get_object_or_404(Checklist, id=checklist_id)
    checklists = Checklist.objects.all()
    filter_type = request.GET.get('filter')
    if filter_type == 'id-sort':
        id_sort = request.GET.get('id-sort')
        if id_sort == 'asc':
            checklists = checklists.order_by('id')
        elif id_sort == 'desc':
            checklists = checklists.order_by('-id')
    elif filter_type == 'name':
        name = request.GET.get('name')
        if name:
            checklists = checklists.filter(name__icontains=name)
    elif filter_type == 'status':
        status = request.GET.get('status')
        if status:
            checklists = checklists.filter(status=status)
    if request.method == 'POST':
        form = ChecklistForm(request.POST, instance=checklist)
        if form.is_valid():
            form.save()
            return redirect(reverse('testing:checklist_details', kwargs={'id': checklist.id}))  # Используем reverse для генерации URL
    else:
        form = ChecklistForm(instance=checklist)
    return render(request, 'testing/checklist_edit.html', {'form2': form, 'checklist': checklist,'checklists': checklists})

def test_case_details(request, id):
    case = get_object_or_404(TestCase, pk=id)
    cases = TestCase.objects.all()
    filter_type = request.GET.get('filter')
    if filter_type == 'id-sort':
        id_sort = request.GET.get('id-sort')
        if id_sort == 'asc':
            cases = cases.order_by('id')
        elif id_sort == 'desc':
            cases = cases.order_by('-id')
    elif filter_type == 'name':
        name = request.GET.get('name')
        if name:
            cases = cases.filter(name__icontains=name)
    elif filter_type == 'status':
        status = request.GET.get('status')
        if status:
            cases = cases.filter(status=status)
    return render(request, 'testing/test_case_details.html', {'case': case, 'cases': cases})

def checklist_details(request, id):
    checklist = get_object_or_404(Checklist, pk=id)
    checklists = Checklist.objects.all()
    filter_type = request.GET.get('filter')
    if filter_type == 'id-sort':
        id_sort = request.GET.get('id-sort')
        if id_sort == 'asc':
            checklists = checklists.order_by('id')
        elif id_sort == 'desc':
            checklists = checklists.order_by('-id')
    elif filter_type == 'name':
        name = request.GET.get('name')
        if name:
            checklists = checklists.filter(name__icontains=name)
    elif filter_type == 'status':
        status = request.GET.get('status')
        if status:
            checklists = checklists.filter(status=status)
    return render(request, 'testing/checklist_details.html', {'checklist': checklist, 'checklists': checklists})


def update_status(request, case_id):
    case = get_object_or_404(TestCase, id=case_id)
    if request.method == 'POST':
        status = request.POST.get('status')
        if status in dict(TestCase.STATUS_CHOICES):
            case.status = status
            case.save()
    return redirect('testing:test_case_details', id=case_id)

def update_checkstatus(request, checklist_id):
    checklist = get_object_or_404(Checklist, id=checklist_id)
    if request.method == 'POST':
        status = request.POST.get('status')
        if status in dict(Checklist.STATUS_CHOICES):
            checklist.status = status
            checklist.save()
    return redirect('testing:checklist_details', id=checklist_id)


#testplan

def test_plans(request):
    testplans = TestPlan.objects.all()
    filter_type = request.GET.get('filter')
    if filter_type == 'id-sort':
        id_sort = request.GET.get('id-sort')
        if id_sort == 'asc':
            testplans = testplans.order_by('id')
        elif id_sort == 'desc':
            testplans = testplans.order_by('-id')
    elif filter_type == 'name':
        name = request.GET.get('name')
        if name:
            testplans = testplans.filter(name__icontains=name)
    elif filter_type == 'status':
        status = request.GET.get('status')
        if status:
            testplans = testplans.filter(status=status)
    return render(request, 'testing/test_plans.html', {'testplans': testplans})

def create_testplan(request):
    testplans = TestPlan.objects.all()
    if request.method == 'POST':
        form = TestPlanForm(request.POST)
        if form.is_valid():
            form.save()
            form = TestPlanForm()  # Очистка формы для нового ввода
            return redirect('/testing/test_plans/')
    else:
        form = TestPlanForm()

    return render(request, 'testing/testplan_create.html', {'form3': form, 'testplans': testplans})

def edit_testplan(request, testplan_id):
    testplan = get_object_or_404(TestPlan, id=testplan_id)
    testplans = TestPlan.objects.all()
    filter_type = request.GET.get('filter')
    if filter_type == 'id-sort':
        id_sort = request.GET.get('id-sort')
        if id_sort == 'asc':
            testplans = testplans.order_by('id')
        elif id_sort == 'desc':
            testplans = testplans.order_by('-id')
    elif filter_type == 'name':
        name = request.GET.get('name')
        if name:
            testplans = testplans.filter(name__icontains=name)
    elif filter_type == 'status':
        status = request.GET.get('status')
        if status:
            testplans = testplans.filter(status=status)
    if request.method == 'POST':

testing/templates/testing/auto_test_detail.html
<!-- auto_test_detail.html -->
{% extends 'testing/base.html' %}

{% block content %}

{% include 'testing/sidebar_content.html' %}

<div class="check-list-container">
    <a href="{% url 'testing:auto_test_create' %}" class="create-checklist-button">Добавить новый автотест</a>
    <a href="{% url 'testing:runall_autotests' %}" class="run_autotest-button">Запустить автотесты</a>
    <h4>Автотесты:</h4>
    <div class="created-checklist">
        {% for auto_test in auto_tests %}
        <a href="{% url 'testing:auto_test_detail' auto_test.id %}" class="checklist-link">
            <div class="checklist-item {% if auto_test.status == 'not_tested' %}not-tested{% elif auto_test.status == 'passed' %}passed{% elif auto_test.status == 'failed' %}failed{% endif %}">
                <strong>{{ auto_test.name }} - Статус: {{ auto_test.status }}</strong>         
            </div>
        </a>
        {% endfor %}
    </div>
</div>

    <div class="check-list-info">
        <div class="autotest-details">
            <h2>Название: {{ auto_test.name }}</h2>
            <h3>Описание: {{ auto_test.description }}</h3>
            <h6>Статус: {{ auto_test.status }}</h6>
            <h4>Создано: {{ auto_test.creation_date|date:"d.m.Y H:i" }}</h4>
            <h5>Обновлено: {{ auto_test.updated_at|date:"d.m.Y H:i" }}</h5>
            <h7>Последний запуск: {{ auto_test.last_run_date|date:"d.m.Y H:i" }}</h7>
            <a href="{% url 'testing:run_auto_test' auto_test.pk %}" class="run_autotest2-button">Run</a>
            <a href="{% url 'testing:auto_test_edit' auto_test.id %}" class="edit-clbutton">Редактировать</a>  
            <form action="{% url 'testing:auto_test_delete' auto_test.id %}" method="post" class="delete-clform">
                {% csrf_token %}
                <button type="submit" class="delete-clbutton">Удалить</button>
            </form>
        </div>
    </div>  
</div>

{% endblock %}

testing/templates/testing/bug_detail.html
{% extends 'testing/base.html' %}
{% load static %}
{% block content %}
{% include 'testing/sidebar_content.html' %}


<div class="check-list-container">
    <a href="{% url 'testing:create_bug' %}" class="create-checklist-button">Создать новый Баг-репорт</a>
    <h4>Баг-репорты:</h4>
    <div class="created-checklist">
        {% for bug in bugs %}
        <a href="{% url 'testing:bug_detail' bug.id %}" class="checklist-link">
            <div class="checklist-item {% if checklist.status == 'not_tested' %}not-tested{% elif checklist.status == 'passed' %}passed{% elif checklist.status == 'failed' %}failed{% endif %}">
                <strong>{{ bug.summary }}</strong>- </strong> - {{ bug.priority }}
            </div>
        </a>
        {% endfor %}
    </div>
</div>

    <div class="bug-info">
        <div class="bug-details">
            <h2>Название: {{ bug.summary }}</h2>
            <h3>Описание: {{ bug.description }}</h3>
            <h4>Создано: {{ bug.created_at|date:"d.m.Y H:i" }}</h4>
            <h5>Обновлено: {{ bug.updated_at|date:"d.m.Y H:i" }}</h5>
            <h6>Приоритет: {{ bug.priority }}</h6>
            <form action="{% url 'testing:delete_bug' bug.id %}" method="post" class="delete-clform">
                {% csrf_token %}
                <a href="{% url 'testing:bug_edit' bug.id %}" class="edit-clbutton">Редактировать</a> 
                <button type="submit" class="delete-clbutton">Удалить</button>
            </form>
        </div>
    </div>  
</div>

{% endblock %}

testing/templates/testing/bug_edit.html
{% extends 'testing/base.html' %}
{% load static %}
{% block content %}
{% include 'testing/sidebar_content.html' %}
<div class="check-list-container">
    <a href="{% url 'testing:create_bug' %}" class="create-checklist-button">Создать новый Баг-репорт</a>
    <h4>Баг-репорты:</h4>
    <div class="created-checklist">
        {% for bug in bugs %}
        <a href="{% url 'testing:bug_detail' bug.id %}" class="checklist-link">
            <div class="checklist-item {% if checklist.status == 'not_tested' %}not-tested{% elif checklist.status == 'passed' %}passed{% elif checklist.status == 'failed' %}failed{% endif %}">
                <strong>{{ bug.summary }}</strong>- </strong> - {{ bug.priority }}
            </div>
        </a>
        {% endfor %}
    </div>


    <div class="checkform-container">
        <form method="post" class="test-case-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form2.name.id_for_label }}">Название:</label>
                {{ form4.summary }}
            </div>
            <div class="form-group">
                <label for="{{ form2.description.id_for_label }}">Описание:</label>
                {{ form4.description }}
            </div>
            <div class="form-group">
                <label for="{{ form4.description.id_for_label }}">Приоритет:</label>
                {{ form4.priority }}
            </div>
             
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>


{% endblock %}

testing/templates/testing/bug_list.html
{% extends 'testing/base.html' %}
{% load static %}
{% block content %}
{% include 'testing/sidebar_content.html' %}


<div class="check-list-container">
    <a href="{% url 'testing:create_bug' %}" class="create-checklist-button">Создать новый Баг-репорт</a>
    <h4>Баг-репорты:</h4>
    <div class="created-checklist">
        {% for bug in bugs %}
        <a href="{% url 'testing:bug_detail' bug.id %}" class="checklist-link">
            <div class="checklist-item {% if checklist.status == 'not_tested' %}not-tested{% elif checklist.status == 'passed' %}passed{% elif checklist.status == 'failed' %}failed{% endif %}">
                <strong>{{ bug.summary }}</strong>- </strong> - {{ bug.priority }}
            </div>
        </a>
        {% endfor %}
    </div>
</div>



{% endblock %}

testing/templates/testing/create_bug.html
{% extends 'testing/base.html' %}
{% load static %}
{% block content %}
{% include 'testing/sidebar_content.html' %}
<div class="check-list-container">
    <a href="{% url 'testing:create_bug' %}" class="create-checklist-button">Создать новый Баг-репорт</a>
    <h4>Баг-репорты:</h4>
    <div class="created-checklist">
        {% for bug in bugs %}
        <a href="{% url 'testing:bug_detail' bug.id %}" class="checklist-link">
            <div class="checklist-item {% if checklist.status == 'not_tested' %}not-tested{% elif checklist.status == 'passed' %}passed{% elif checklist.status == 'failed' %}failed{% endif %}">
                <strong>{{ bug.summary }}</strong>- </strong> - {{ bug.priority }}
            </div>
        </a>
        {% endfor %}
    </div>


    <div class="checkform-container">
        <form method="post" class="test-case-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form2.name.id_for_label }}">Название:</label>
                {{ form4.summary }}
            </div>
            <div class="form-group">
                <label for="{{ form2.description.id_for_label }}">Описание:</label>
                {{ form4.description }}
            </div>
            <div class="form-group">
                <label for="{{ form4.description.id_for_label }}">Приоритет:</label>
                {{ form4.priority }}
            </div>
          
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>


{% endblock %}

testing/templates/testing/sidebar_content.html
            
<div class="sidebar">
    <h3>Тестовый проект</h3>
    <div class="menu">
        <button class="menu-toggle">Тесты</button>
        <ul class="menu-items">
            <li><a href="{% url 'testing:manual_tests' %}">Тест-кейсы</a></li>
            <li><a href="{% url 'testing:check_list' %}">Чек-листы</a></li>
            <li><a href="{% url 'testing:test_plans' %}">Тест-план</a></li>
        </ul>
    <ul class="menu-item-auto">
        <li><a href="{% url 'testing:auto_test_list' %}">Автотесты</a></li>
        <li><a href="{% url 'testing:bug_list' %}">Баг-репорты</a></li>
        <li><a href="{% url 'testing:statistics' %}">Статистика</a></li>
    </ul>
</div>



testing/templates/testing/test_case_details.html
{% extends 'testing/base.html' %}
{% load static %}
{% block content %}  
{% include 'testing/sidebar_content.html' %}

<!-- testing/manual_tests.html -->
<div class="manual-tests-container">
    <a href="{% url 'testing:create_test_case' %}" class="create-test-case-button">Создать новый тест-кейс</a>
    {% include 'testing/filterform.html' %}
    <h4>Тест-кейсы:</h4>
    <div class="created-test-cases">
        {% for case in cases %}
        <a href="{% url 'testing:test_case_details' case.id %}" class="test-case-link">
            <div class="test-case-item {% if case.status == 'not_tested' %}not-tested{% elif case.status == 'passed' %}passed{% elif case.status == 'failed' %}failed{% endif %}">
                <strong>{{ case.name }}</strong> - {{ case.description }}
            </div>
        </a>
        {% endfor %}
    </div>
</div>


<!-- testing/test_case_details.html -->
<div class="test-container">
    <div class="test-case-details">
        <div class="test-case-header">
            <h1 class="header-id">ID</h1>
            <h2 class="header-name">Название</h2>
            <h3 class="header-description">Описание</h3>
            <h5 class="header-steps">Шаги</h5>
            <h6 class="header-expected-result">Ожидаемый результат</h6>
        </div>
        <div class="test-case-content">
            <div class="test-case-section">
                <p>{{ case.id }}</p>
            </div>
            <div class="test-case-section text-left-name">
                <p>{{ case.name }}</p>
            </div>
            <div class="test-case-section text-left-name-2">
                <p>{{ case.description }}</p>
            </div>
            <div class="test-case-section text-left-name-3">
                <p>{{ case.steps }}</p>
            </div>
            <div class="test-case-section text-left-name-4">
                <p>{{ case.expected_result }}</p>
            </div>
        </div>
     
  
    
        
        <div class="form-buttons-container">

            <div class="test-case-date">
                
                Создано: {{ case.created_at|date:"d.m.Y H:i" }}
                
            </div>
            <div class="test-case-date-2">
                <div class="test-case-date-3">
                    Редактировано: {{ case.updated_at|date:"d.m.Y H:i" }}
                </div>
                <form action="{% url 'testing:update_status' case.id %}" method="post" class="status-form">
                    {% csrf_token %}
                    <label for="status">Статус:</label>
                    <select name="status" id="status">
                        <option value="not_tested" {% if case.status == 'not_tested' %}selected{% endif %}>Не проверен</option>
                        <option value="passed" {% if case.status == 'passed' %}selected{% endif %}>Пройден</option>
                        <option value="failed" {% if case.status == 'failed' %}selected{% endif %}>Провален</option>
                    </select>
                    <button type="submit">Обновить статус</button>
                </form>
            </div>
            <a href="{% url 'testing:edit_test_case' case.id %}" class="edit-button">Редактировать</a>  <!-- Добавлена кнопка редактирования -->
            <form action="{% url 'testing:delete_test_case' case.id %}" method="post" class="delete-form">
                {% csrf_token %}
                <button type="submit" class="delete-button">Удалить</button>
            </form>

    </div>
</div>

</div>


<script>
</script>
    
<script src="{% static 'js/keep-scroll-position.js' %}"></script>
{% endblock %}

testing/templates/testing/testplan_details.html
{% extends 'testing/base.html' %}
{% load static %}
{% block content %}
{% include 'testing/sidebar_content.html' %}

<div class="manual-tests-container">
    <a href="{% url 'testing:testplan_create' %}" class="create-test-case-button">Создать новый тест-план</a>
    {% include 'testing/filterform3.html' %}
    <h4>Тест-планы:</h4>
    <div class="created-testplan">
        {% for testplan in testplans %}
        <a href="{% url 'testing:testplan_details' testplan.id %}" class="testplan-link">
            <div class="testplan-item {% if testplan.status == 'not_start' %}not_start{% elif testplan.status == 'in_progress' %}in_progress{% elif testplan.status == 'completed' %}completed{% endif %}">
                <strong>{{ testplan.name }}</strong>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

    <div class="testplan-container">
        <div class="testplan-details">
            <h2>Модуль: {{ testplan.name }}</h2>
            <h9>Описание:</h9>
            <h3>{{ testplan.description }}</h3>
            <h4>Начало: {{ testplan.start_date }}</h4>
            <h5>Конец: {{ testplan.end_date }}</h5>
            <h6>Создано: {{ testplan.created_at|date:"d.m.Y H:i" }}</h6>
            <h7>Обновлено: {{ testplan.updated_at|date:"d.m.Y H:i" }}</h7>
            <h8>Приоритет: {{ testplan.priority }}</h8>
        <form action="{% url 'testing:update_testplanstatus' testplan.id %}" method="post" class="status-planform">
            {% csrf_token %}
            <label for="status">Статус:</label>
            <select name="status" id="status">
                <option value="not_start" {% if testplan.status == 'not_start' %}selected{% endif %}>Не начат</option>
                <option value="in_progress" {% if testplan.status == 'in_progress' %}selected{% endif %}>В процессе</option>
                <option value="completed" {% if testplan.status == 'completed' %}selected{% endif %}>Завершен</option>
            </select>
            <button type="submit">Обновить статус</button>
        </form>
        
            <a href="{% url 'testing:edit_testplan' testplan.id %}" class="edit-plbutton">Редактировать</a>  
            <form action="{% url 'testing:delete_testplan' testplan.id %}" method="post" class="delete-plform">
                {% csrf_token %}
                <button type="submit" class="delete-clbutton">Удалить</button>
            </form>
        </div>
    </div>  
</div>

{% endblock %}